#!/usr/bin/php
<?php
interface employee{
	public function working();
	public function money();
}

class teacher implements employee{
	public function working(){
		echo "教书\n";
	}
	public function money(){
		echo "惨\n";
	}
}

class coder implements employee{
	public function working(){
		echo 'CV操作';
	}
}

function doprint(employee $i){
	$i->working();
}

$a = new teacher;
$b = new coder;
doprint($a);
doprint($b);

?>
